-- require('tokyonight').setup({
--   style = "storm",
-- })
-- vim.cmd("colorscheme tokyonight")
-- vim.cmd("colorscheme catppuccin")
-- vim.cmd("colorscheme oxocarbon")
-- vim.cmd("colorscheme nord")
-- vim.cmd("colorscheme poimandres")
-- vim.cmd("colorscheme github_dark_high_contrast")
-- require("gruvbox").setup({
--   transparent_mode = true,
-- })
vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme cyberdream")
