-- vim.cmd("colorscheme tokyonight")
-- vim.cmd("colorscheme catppuccin")
-- vim.cmd("colorscheme oxocarbon")
-- vim.cmd("colorscheme nord")
-- vim.cmd("colorscheme poimandres")
-- vim.cmd("colorscheme github_dark_high_contrast")
vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme cyberdream")
